apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: profiles/nginx-init.seccomp.json
      # type: RuntimeDefault
  containers:
  - name: nginx
    image: nginx:1.17.1
    imagePullPolicy: IfNotPresent
    # args:
    # - "-text=just made some syscalls!"
    securityContext:
      allowPrivilegeEscalation: false